# -*- coding: utf-8 -*-
"""Multi-variable Linear Regression

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pEjiuOMp_61SvI0kzmfkxQDG98_1OfOn
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

colnames=['area','rooms','price']
dataset = pd.read_csv("https://raw.githubusercontent.com/nishithkotak/machine-learning/master/ex1data2.txt",names=colnames)

dataset

dataset.describe()

area=dataset.iloc[0:dataset.shape[0],0:1]
rooms=dataset.iloc[0:dataset.shape[0],1:2]
price=dataset.iloc[0:dataset.shape[0],2:3]

dataset.shape

# function of normalization
def feature_normalization(x):
    mean=np.mean(x,axis=0)
    std=np.std(x,axis=0)
    x_normalized=(x-mean)/std
    return x_normalized,mean,std

data_norm=dataset.values
m=data_norm.shape[0]
# take the feature vectors
x2=data_norm[:,0:2].reshape(m,2)
x2_norm,mean,std=feature_normalization(x2)

y2=data_norm[:,2:3].reshape(m,1)#price column

x2_norm

theta_array=np.zeros((3,1))

